### ISSUE TITLE
Fails to build on OSX

### ISSUE THREAD

**Issue by tanmaykm** [JuliaWeb/GnuTLS.jl#10] opened 2013-09-23 04:53 UTC
````
WARNING: An exception occured while building binary dependencies.
You may have to take manual steps to complete the installation, see the error message below.
To reattempt the installation, run Pkg.fixup("GnuTLS").

 in build at pkg.jl:412
ERROR: Provider PackageManager failed to satisfy dependency gnutls
 in error at error.jl:21
 in satisfy! at /Users/tan/.julia/BinDeps/src/dependencies.jl:435
 in satisfy! at /Users/tan/.julia/BinDeps/src/dependencies.jl:421
 in anonymous at /Users/tan/.julia/BinDeps/src/dependencies.jl:449
 in include at boot.jl:238
 in include_from_node1 at loading.jl:96
 in anonymous at no file:415
 in cd at file.jl:25
 in cd at pkg/dir.jl:30
 in build at pkg.jl:412
 in __fixup at pkg.jl:464
 in _fixup at pkg.jl:491
 in _fixup at pkg.jl:512
 in _fixup at pkg.jl:511 (repeats 4 times)
 in cd at file.jl:25
 in cd at pkg/dir.jl:30
 in fixup at pkg.jl:515
at /Users/tan/.julia/GnuTLS/deps/build.jl:49
````

Going by the README, I tried switching to master branches of GnuTLS, Homebrew and BinDeps. But that didn't help.

**Comment by sbromberger** [comment] 2015-02-18 18:20
Closing this out for now, since it's unreproducible on current 0.3 and 0.4.

**Closed by sbromberger** 2015-02-18 18:20 UTC
