### ISSUE TITLE
Error on `using`, `getcwd, no such file or directory`

### ISSUE THREAD

**Issue by WestleyArgentum** [JuliaWeb/GnuTLS.jl#15] opened 2014-01-18 19:57 UTC
On OSX 10.9.1, after wiping out ~/.julia:

```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" to list help topics
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.2.0+3 (2013-11-19 21:30 UTC)
 _/ |\__'_|_|_|\__'_|  |  release-0.2/09be0a1 (fork: 3 commits, 3 days)
|__/                   |  x86_64-apple-darwin13.0.0

julia> Pkg.add("Homebrew")
INFO: Initializing package repository /Users/westley/.julia
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
INFO: Cloning cache of BinDeps from git://github.com/JuliaLang/BinDeps.jl.git
INFO: Cloning cache of Homebrew from git://github.com/JuliaLang/Homebrew.jl.git
INFO: Cloning cache of URIParser from git://github.com/loladiro/URIParser.jl.git
INFO: Installing BinDeps v0.2.12
INFO: Installing Homebrew v0.0.4
INFO: Installing URIParser v0.0.1
INFO: Building Homebrew
INFO: Cloning brew from https://github.com/staticfloat/homebrew.git
Cloning into '/Users/westley/.julia/Homebrew/deps/usr'...
remote: Counting objects: 2899, done.
remote: Compressing objects: 100% (2764/2764), done.
remote: Total 2899 (delta 66), reused 944 (delta 21)
Receiving objects: 100% (2899/2899), 1.51 MiB | 671.00 KiB/s, done.
Resolving deltas: 100% (66/66), done.
Checking connectivity... done
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  259k  100  259k    0     0   718k      0 --:--:-- --:--:-- --:--:--  718k
Cloning into '/Users/westley/.julia/Homebrew/deps/usr/Library/Taps/staticfloat-juliadeps'...
remote: Reusing existing pack: 311, done.
remote: Total 311 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (311/311), 71.75 KiB | 0 bytes/s, done.
Resolving deltas: 100% (169/169), done.
Checking connectivity... done
Tapped 28 formula
HEAD is now at 7dbece7 Merge branch 'kegpkg' of github.com:staticfloat/homebrew into kegpkg
HEAD is now at e7a2203 Tab fix didn't work, revert to old behavior
INFO: REQUIRE updated.

julia> Pkg.add("GnuTLS")
INFO: Cloning cache of GnuTLS from git://github.com/loladiro/GnuTLS.jl.git
INFO: Installing GnuTLS v0.0.0
INFO: Building GnuTLS
INFO: REQUIRE updated.

julia> using GnuTLS
ERROR: getcwd: No such file or directory
 in include at boot.jl:238
 in include_from_node1 at loading.jl:114
 in reload_path at loading.jl:140
 in _require at loading.jl:58
 in require at loading.jl:43
at /Users/westley/.julia/GnuTLS/src/../deps/build.jl:1
at /Users/westley/.julia/GnuTLS/src/GnuTLS.jl:5
```

Any ideas? I've had this working on this computer before, but from a fresh install it's broken. This is unfortunately blocking people from using things like Requests.jl, etc...

**Comment by sbromberger** [comment] 2015-02-18 20:38
@WestleyArgentum closing this out since I can't reproduce it. If you're still having this error, please let me know and I'll be happy to reopen.

**Closed by sbromberger** 2015-02-18 20:38 UTC

**Comment by WestleyArgentum** [comment] 2015-02-19 15:33
Totally forgot about this, but I haven't had problems since,  thanks!
